import { afterEach, expect, it, vi } from "vitest";
import { AlRoomDeviceEditor } from "../src/al-room-device-editor";
import { newGroup, newStimulus } from "../src/model";
import { newFixture } from "../src/room-fixtures";
import { roomsConfig } from "./fixtures";
import type { HomeAssistant } from "../src/types";
vi.mock("../src/floorplan-renderer",()=>({FloorplanRenderer:class {setParts(){}setPlacement(){}setActivity(){}dispose(){}}}));
afterEach(()=>document.body.replaceChildren());
it("starts with the 2D outline, places a room input, and reuses a saved model",async()=>{
  const el=new AlRoomDeviceEditor();const config=roomsConfig();
  config.groups=[{...newGroup("room","area"),bounds:[[0,0,10],[4,4,13]],stimuli:[newStimulus("binary_sensor.corner")],fixtures:[{...newFixture("binary_sensor.second"),position:[2,2,12],yaw:80}]}];el.config=config;
  el.hass={states:{},callWS:vi.fn().mockResolvedValue(["binary_sensor.corner","binary_sensor.second"].map(entity=>({entity,area_id:null,manufacturer:"Acme",model:"PIR",platform:"zwave_js",device_class:"motion",entity_name:"Motion"})))} as unknown as HomeAssistant;
  document.body.append(el);await el.updateComplete;
  const room=el.shadowRoot!.querySelector<HTMLSelectElement>("#device-room")!;
  room.value="room";room.dispatchEvent(new Event("change"));await el.updateComplete;
  expect(el.shadowRoot!.querySelector("al-room-plan")).not.toBeNull();expect(el.shadowRoot!.querySelector("al-floorplan-viewer")).toBeNull();
  el.shadowRoot!.querySelector<HTMLButtonElement>('[data-entity="binary_sensor.corner"]')!.click();await el.updateComplete;
  el.shadowRoot!.querySelector("al-room-plan")!.dispatchEvent(new CustomEvent("al-fixture-position",{detail:[0,0,12],bubbles:true}));await el.updateComplete;
  const changed=vi.fn((e:Event)=>{el.config=(e as CustomEvent).detail;});el.addEventListener("al-change",changed);
  el.shadowRoot!.querySelector<HTMLButtonElement>("#save-fixture")!.click();await el.updateComplete;
  expect(el.config.groups[0]!.fixtures![1]!.position).toEqual([0,0,12]);expect(config.groups[0]!.fixtures).toHaveLength(1);
  const name=el.shadowRoot!.querySelector<HTMLInputElement>("#profile-name")!;name.value="My sensor";name.dispatchEvent(new Event("input"));await el.updateComplete;
  el.shadowRoot!.querySelector<HTMLButtonElement>("#save-profile")!.click();await el.updateComplete;
  expect(el.config.sensor_profiles![0]!.name).toBe("My sensor");expect(el.config.sensor_profiles![0]).not.toHaveProperty("position");
  el.shadowRoot!.querySelector<HTMLButtonElement>('[data-entity="binary_sensor.second"]')!.click();await el.updateComplete;
  expect(el.shadowRoot!.querySelector<HTMLSelectElement>("#sensor-profile")!.value).toBe(el.config.sensor_profiles![0]!.id);
  [...el.shadowRoot!.querySelectorAll("button")].find(b=>b.textContent==="Apply profile")!.click();await el.updateComplete;
  el.shadowRoot!.querySelector<HTMLButtonElement>("#save-fixture")!.click();await el.updateComplete;
  expect(el.config.groups[0]!.fixtures![0]!.position).toEqual([2,2,12]);expect(el.config.groups[0]!.fixtures![0]!.yaw).toBe(80);
  el.disabled=true;await el.updateComplete;
  const calls=changed.mock.calls.length;el.shadowRoot!.querySelector<HTMLButtonElement>("#save-fixture")!.click();expect(changed).toHaveBeenCalledTimes(calls);
});
